all:
  hosts:
    node1:
      ansible_host: 172.18.8.101
      ip: 172.18.8.101
      access_ip: 172.18.8.101
    node2:
      ansible_host: 172.18.8.102
      ip: 172.18.8.102
      access_ip: 172.18.8.102
    node3:
      ansible_host: 172.18.8.103
      ip: 172.18.8.103
      access_ip: 172.18.8.103
    node4:
      ansible_host: 172.18.8.104
      ip: 172.18.8.104
      access_ip: 172.18.8.104
    node5:
      ansible_host: 172.18.8.105
      ip: 172.18.8.105
      access_ip: 172.18.8.105
    node6:
      ansible_host: 172.18.8.106
      ip: 172.18.8.106
      access_ip: 172.18.8.106
  children:
    kube_control_plane:
      hosts:
        node1:
        node2:
        node3:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
        node4:
        node5:
        node6:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
