apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    {{- include "nginx.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8080
      targetPort: http2
      protocol: TCP
      name: http2
  selector:
    {{- include "nginx.selectorLabels" . | nindent 4 }}
