---
all:
  hosts:
    jenkins-master-01:
      ansible_host: 51.250.12.188
    jenkins-agent-01:
      ansible_host: 158.160.119.193
  children:
    jenkins:
      children:
        jenkins_masters:
          hosts:
            jenkins-master-01:
        jenkins_agents:
          hosts:
              jenkins-agent-01:
  vars:
    ansible_connection_type: paramiko
    ansible_user: centos
    ansible_ssh_private_key_file: /home/alex/.ssh/id_ed25519